# Generated by Django 5.1.1 on 2024-10-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_food_category_remove_food_image_food_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.category'),
            preserve_default=False,
        ),
    ]
