# Generated by Django 5.1.1 on 2024-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_food_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'kategoriya', 'verbose_name_plural': 'kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name'], 'verbose_name': 'ocqat soni', 'verbose_name_plural': 'ocqat nomi'},
        ),
        migrations.AddField(
            model_name='food',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
